### ISSUE TITLE
Compare Model Instances

### ISSUE THREAD

**Issue by sposs** [rfk/dexml#10]
If I have something like

```
class A(dexml.Model):
  a_field = fields.String()

class B(dexml.Model):
  b_field = fields.Model(A)
```

And I want to compare 2 instances of B (for example if 2 xmls arrive and I want to check the correspondence). I was expecting I should do

```
class A(dexml.Model):
    a_field = fields.String()
    def __eq__(self,other):
        if self.a_field != other.a_field
             return False
        return True

class B(dexml.Model):
    b_field = fields.Model(A)
    def __eq__(self,other):
        if self.b_field != other.b_field:
            return False
        return True
```

or something in those lines. The problem is that fields.\* do not forward the 'eq' operator to what they represent... How could I fix this situation?

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
