### ISSUE TITLE
XPath Support?

### ISSUE THREAD

**Issue by jmmills** [rfk/dexml#12]
I'm a fairly new Python programmer but coming from extensive experience in Perl, I have an XML API I need to write a parser around and I came across your module when looking for the Python equivalent of Perl's XML-Rabbit (http://search.cpan.org/~robins/XML-Rabbit-0.4.0/lib/XML/Rabbit.pm).
I was wondering, do you plan on supporting XPath? Currently how do you define an object model that doesn't exactly match up to the structure of the XML Data? What if I want to define a class attribute that maps to a Node attribute rather than a NodeElement?

Maybe I missed something in examples?

**Comment by rfk** [comment]
Currently you have to map the object model pretty closely to the XML data model, there's no xpath support or similar.  I have no plans to add such functionality myself (I'm not actively developing this project anymore, it's pretty much in maintenance mode) but I'd be happy to offer advice and review if you wanted to take a crack at implementing it yourself.

**Comment by jmmills** [comment]
Thanks for the reply. If this project is in maint only at this point, could you point me in the direction of an active project for object models in python around XML data?
Perhaps if there is none, I will pursue porting the Perl version to Python and keeping a parallel project.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
