### ISSUE TITLE
unit test fails

### ISSUE THREAD

**Issue by sknauth** [rfk/dexml#16]
Latest commits broke the unit tests.

**Comment by rfk** [comment]
So they did, thanks for pointing that out.  I thought I'd run those but obviously not!  I'll see about setting up some travis integration to get proper warning of these things in future...

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
