### ISSUE TITLE
mixed tags

### ISSUE THREAD

**Issue by defgsus** [rfk/dexml#21]
Hi there,
dexml does not seem to support mixed sub-tags. It ends generating lists (or dicts) at the first differing tag, for example:
```python
import dexml

class Sub1(dexml.Model):
    arg = dexml.fields.String()

class Sub2(dexml.Model):
    arg = dexml.fields.String()

class Main(dexml.Model):
    sub1 = dexml.fields.List(Sub1)
    sub2 = dexml.fields.List(Sub2)

root = Main.parse("""
<Main>
    <Sub1 arg="a"></Sub1>
    <Sub1 arg="b"></Sub1>
    <Sub2 arg="c"></Sub2>
    <Sub1 arg="d"></Sub1>
</Main>
""")

assert(len(root.sub1) == 3)
assert(len(root.sub2) == 1)
```
I'd expect `len(root.sub1)` to be three, but it's two. The last Sub1 does not seem to be parsed. Is that a bug or a feature? Unfortunately i do not have control over the layout of the xml i'm trying to parse

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
