### ISSUE TITLE
AttributeError: 'List' object has no attribute 'append'

### ISSUE THREAD

**Issue by terencecollins** [rfk/dexml#25]
class Track(dexml.Model):
    def __init__(self, number = None):
        self.number = fields.String()
        self.total_length = fields.String()
        self.subtracks = fields.List(SubTrack)

this_track = Track()
this_subtrack = SubTrack()
this_track.subtracks.append(SubTrack)

produces the error 
AttributeError: 'List' object has no attribute 'append'

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
