### ISSUE TITLE
MiniDom is Dead Slow

### ISSUE THREAD

**Issue by asprague** [rfk/dexml#4]
When dealing with a lot of files (100+), minidom starts to become the bottleneck in an application really quickly. Parsing 1000 small (>10kb each) takes a bit over 2 minutes (cProfile output edited to show only relevant sections):

```
 ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   1000    0.035    0.000  129.661    0.130 env/lib/python2.6/site-packages/dexml/__init__.py:281(parse)
   1000    0.006    0.000  124.224    0.124 env/lib/python2.6/site-packages/dexml/__init__.py:527(_make_xml_node)
   1000    0.016    0.000  124.216    0.124 /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/xml/dom/minidom.py:1914(parse)
   1000    0.012    0.000  124.200    0.124 /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/xml/dom/expatbuilder.py:911(parse)
   1000    0.012    0.000  123.583    0.124 /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/xml/dom/expatbuilder.py:197(parseFile)
   2470    1.172    0.000  123.507    0.050 {built-in method Parse}
 256003    0.137    0.000  120.444    0.000 /private/var/tmp/python/python-56~121/2.6/python/Modules/pyexpat.c:604(StartElement)
 256003   42.367    0.000  120.303    0.000 /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/xml/dom/expatbuilder.py:743(start_element_handler)
1249305   68.778    0.000   68.971    0.000 /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/xml/dom/minidom.py:349(__init__)
 256003    8.334    0.000    8.334    0.000 /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/xml/dom/minidom.py:652(__init__)
```

Unfortunately, I couldn't find a good drop-in replacement for `minidom`. `PyXML` is deprecated and broken, and `libxml2dom` and `qtxmldom` aren't very friendly to install (I'm working on OS X right now). 

The main functional alternatives are either `SAX` or `ElementTree` based. I've never used `SAX`, and `ElementTree` seems to have a lot more community support. 

Would you be open to replacing `minidom` with `ElementTree`?

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
