### ISSUE TITLE
tag name doesn't work with foriegn keys

### ISSUE THREAD

**Issue by fredkingham** [rfk/dexml#6]
e.g.

class Onion(dexml.Model):
    price = fields.Integer(tagname="price")

class VegetableBasket(dexml.Model):
    purple_onions = fields.Model(Onion, tagname="purple_onion")

a = serializers.Onion(price=10)
b = serializers.VegetableBasket(purple_onions = a)
b.render()

'<?xml version="1.0" ?><VegetableBasket><Onion><price>10</price></Onion></VegetableBasket>'

is this by design?

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
