### ISSUE TITLE
No support for fields.List(tagname='.')

### ISSUE THREAD

**Issue by allfro** [rfk/dexml#7]
Hi,

Say you are trying to parse the following xml:

``` xml
<a v="1">
<c d="2"/>
<c d="2"/>
<c d="2"/>
<e f="3"/>
<e f="3"/>
</a>
```

Using the class definitions:

``` python
class c(Model):
  d = fields.Integer()

class e(Model):
  f = fields.Integer()


class a(Model):
  v = fields.Integer()
  cs = fields.List(c, tagname=".", required=False)
  es = fields.List(e, tagname=".", required=False)
```

This does not work since fields.List(tagname='.') does not appear to be supported. Is there anyway we can implement this? I know the XML schema is terrible but I didn't write it. Unfortunately, I need to parse it :|. Any ideas would be greatly appreciated. I could implement the patch with some direction.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
