### ISSUE TITLE
Parsing a tag with unknown number of attributes and unknown attribute names

### ISSUE THREAD

**Issue by mirkodandrea** [rfk/dexml#8]
I have this xml to parse, in which the number of attributes and the attributes names of the inner tags are not defined a priori.

``` xml
<table>
    <columnIds A="precip" C="velocity" B="discharge" D="index" />
    <columnTypes A="float" C="double" B="float" D="int" />
    <columnUnits A="mm" C="m/s" B="m3" D="-" />
    <row A="0.1" C="0.03" B="0.2" D="0" />
    <row A="1.1" C="1.03" B="1.2" D="1" />
    <row A="2.1" C="2.03" B="2.2" D="2" />
    <row A="3.1" C="3.03" B="3.2" D="3" />
</table>
```

It would be useful if the parser could return this information as a dictionary with the unmatched attributes within the parsed object.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
